# Generated by Django 4.0.5 on 2022-06-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
